import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Sample Next Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
